"""
simulate.py
Generates simulated pick CSVs (all 72 matches) and match results for
end-to-end testing before the tournament begins.

Pick files are named simulation_1, simulation_2, etc. so they are easy
to identify and remove with clear_simulation.yml when testing is done.
You can also create your own test picks manually using the same naming pattern.

Usage:
  python simulate.py --participants 5
"""

import argparse
import csv
import json
import os
import random
import sys

# parse_results.py is in the same directory — import canonical match data from it.
sys.path.insert(0, os.path.dirname(__file__))
from parse_results import GROUP_MATCHES

# Build (num, grp, t1, t2) tuples used throughout this script.
MATCHES = [(num, grp, t1, t2) for num, grp, t1, t2 in GROUP_MATCHES]


# ── Knockout bracket data ─────────────────────────────────────────────────────

# Simulated R32 teams (M73–M88) — representative teams for testing only.
# In production, these come from knockout_bracket.json generated by parse_results.py.
R32_SIM_TEAMS = {
    73: ('Brazil',          'Morocco'),
    74: ('France',          'Norway'),
    75: ('Spain',           'Ecuador'),
    76: ('Germany',         'Switzerland'),
    77: ('Argentina',       'Mexico'),
    78: ('Netherlands',     'Senegal'),
    79: ('England',         'Ivory Coast'),
    80: ('Portugal',        'Colombia'),
    81: ('Belgium',         'United States'),
    82: ('Croatia',         'Japan'),
    83: ('South Korea',     'Saudi Arabia'),
    84: ('Uruguay',         'Egypt'),
    85: ('Turkey',          'Canada'),
    86: ('Austria',         'Sweden'),
    87: ('Tunisia',         'Ghana'),
    88: ('Panama',          'Australia'),
}

# KO topology — canonical source is bracket.js (R16/QF/SF) / sim_core.js.
# Mirrored here for the Python simulation context.
R16_FEEDS = {
    89: (74, 77),  90: (73, 75),  91: (76, 78),  92: (79, 80),
    93: (83, 84),  94: (81, 82),  95: (86, 88),  96: (85, 87),
}
QF_FEEDS = {
     97: (89, 90),  98: (93, 94),  99: (91, 92), 100: (95, 96),
}
SF_FEEDS = {
    101: (97, 98), 102: (99, 100),
}

KO_MATCH_ORDER = (
    list(range(73, 89)) +   # R32
    list(range(89, 97)) +   # R16
    list(range(97, 101)) +  # QF
    [101, 102, 103, 104]    # SF, 3rd, Final
)


def ko_round_label(m):
    """Return a short round label for a knockout match number."""
    if 73 <= m <= 88:  return 'R32'
    if 89 <= m <= 96:  return 'R16'
    if 97 <= m <= 100: return 'QF'
    if m in (101, 102): return 'SF'
    if m == 103:        return '3rd'
    if m == 104:        return 'Final'
    return ''


def simulate_ko_bracket(r32_teams):
    """Pick random winners round-by-round through the entire knockout bracket.
    Returns {match_num: winner_name} for all 32 matches (M73–M104).
    """
    winners = {}
    match_teams = dict(r32_teams)  # {m: (home, away)}

    # R32
    for m, (home, away) in r32_teams.items():
        winners[m] = random.choice([home, away])

    # R16 → QF → SF
    for feeds in (R16_FEEDS, QF_FEEDS, SF_FEEDS):
        for m, (f1, f2) in feeds.items():
            match_teams[m] = (winners[f1], winners[f2])
            winners[m] = random.choice([winners[f1], winners[f2]])

    # 3rd place: losers of both SF matches
    loser101 = (match_teams[101][0] if winners[101] == match_teams[101][1]
                else match_teams[101][1])
    loser102 = (match_teams[102][0] if winners[102] == match_teams[102][1]
                else match_teams[102][1])
    match_teams[103] = (loser101, loser102)
    winners[103] = random.choice([loser101, loser102])

    # Final
    match_teams[104] = (winners[101], winners[102])
    winners[104] = random.choice([winners[101], winners[102]])

    return winners, match_teams


def generate_knockout_bracket(r32_teams):
    """Write data/knockout_bracket.json with confirmed=True and R32 teams."""
    os.makedirs('data', exist_ok=True)
    data = {
        'confirmed': True,
        'wikipedia_seen': True,
        'round_of_32': {
            str(m): {'home': home, 'away': away, 'wiki_home': home, 'wiki_away': away}
            for m, (home, away) in r32_teams.items()
        },
    }
    path = 'data/knockout_bracket.json'
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2)
    print(f'Generated knockout bracket → {path}')


def generate_knockout_picks(pool_id, participant_num, r32_teams):
    """Write a simulated knockout picks CSV for one participant."""
    folder = f'picks/knockout/{pool_id}'
    os.makedirs(folder, exist_ok=True)
    filename = f'{folder}/wc26_knockout_simulation-{participant_num}.csv'
    winners, match_teams = simulate_ko_bracket(r32_teams)
    with open(filename, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['match', 'round', 'matchup', 'pick'])
        for m in KO_MATCH_ORDER:
            home, away = match_teams.get(m, ('', ''))
            writer.writerow([m, ko_round_label(m), f'{home} v {away}', winners.get(m, '')])
    print(f'  Generated: {filename}')


def random_outcome():
    return random.choice(['W1', 'Draw', 'W2'])


def outcome_label(outcome, t1, t2):
    if outcome == 'W1':   return t1
    if outcome == 'Draw': return 'Draw'
    return t2


def random_score(outcome):
    if outcome == 'W1':
        h = random.randint(1, 4)
        a = random.randint(0, h - 1)
    elif outcome == 'W2':
        a = random.randint(1, 4)
        h = random.randint(0, a - 1)
    else:
        s = random.randint(0, 2)
        h = a = s
    return h, a


def generate_picks(pool_id, participant_num):
    folder = f'picks/group/{pool_id}'
    os.makedirs(folder, exist_ok=True)
    filename = f'{folder}/wc26_group_simulation-{participant_num}.csv'
    with open(filename, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['match', 'group', 'matchup', 'pick'])
        for num, grp, t1, t2 in MATCHES:
            outcome = random_outcome()
            label   = outcome_label(outcome, t1, t2)
            writer.writerow([num, grp, f'{t1} v {t2}', label])
    print(f'  Generated: {filename}')


def _check_no_real_results(path, force):
    """Abort if the results file already contains real (non-empty) data, unless --force."""
    if not os.path.exists(path):
        return
    with open(path, encoding='utf-8') as f:
        lines = [l for l in f if l.strip() and not l.startswith('match')]
    if lines and not force:
        print(f'\nERROR: {path} already contains {len(lines)} result(s).')
        print('This looks like real tournament data. Pass --force to overwrite anyway.')
        raise SystemExit(1)


def generate_ko_results(r32_teams, force=False):
    """Write results/knockout_results.csv with simulated winners for all 32 KO matches."""
    os.makedirs('results', exist_ok=True)
    path = 'results/knockout_results.csv'
    _check_no_real_results(path, force)
    winners, _ = simulate_ko_bracket(r32_teams)
    with open(path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['match', 'winner'])
        for m in KO_MATCH_ORDER:
            writer.writerow([m, winners.get(m, '')])
    print(f'Generated results for all 32 KO matches → {path}')


def generate_results(force=False):
    os.makedirs('results', exist_ok=True)
    path = 'results/group_results.csv'
    _check_no_real_results(path, force)
    with open(path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['match', 'home_score', 'away_score', 'outcome'])
        for num, grp, t1, t2 in MATCHES:
            outcome    = random_outcome()
            home, away = random_score(outcome)
            writer.writerow([num, home, away, outcome])
    print(f'Generated results for all 72 matches → {path}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--participants', type=int, default=5)
    parser.add_argument('--stage', choices=['group', 'knockout', 'all'], default='all',
                        help='Which stage to simulate (default: all)')
    parser.add_argument('--seed', type=int, default=None,
                        help='Random seed for reproducible output (default: random)')
    parser.add_argument('--force', action='store_true',
                        help='Overwrite results CSVs even if they contain real data (dangerous)')
    args = parser.parse_args()

    if args.seed is not None:
        random.seed(args.seed)
        print(f'Random seed: {args.seed}')

    if args.stage in ('group', 'all'):
        print(f'\nGenerating {args.participants} participants × 2 pools (all 72 group matches)...')
        for pool_id in ['swiftly', 'fandf']:
            print(f'\n  Pool: {pool_id}')
            for n in range(1, args.participants + 1):
                generate_picks(pool_id, n)
        print('\nGenerating results for all 72 group matches...')
        generate_results(force=args.force)

    if args.stage in ('knockout', 'all'):
        print(f'\nGenerating knockout bracket (confirmed R32 teams)...')
        generate_knockout_bracket(R32_SIM_TEAMS)
        print(f'\nGenerating {args.participants} participants × 2 pools (all 32 knockout matches)...')
        for pool_id in ['swiftly', 'fandf']:
            print(f'\n  Pool: {pool_id}')
            for n in range(1, args.participants + 1):
                generate_knockout_picks(pool_id, n, R32_SIM_TEAMS)
        print('\nGenerating results for all 32 KO matches...')
        generate_ko_results(R32_SIM_TEAMS, force=args.force)

    print('\nDone. Run aggregate_picks.py next to update the leaderboard data.')
