"""
simulate.py
Generates simulated pick CSVs (all 72 matches) and match results for
end-to-end testing before the tournament begins.

Pick files are named simulation_1, simulation_2, etc. so they are easy
to identify and remove with clear_simulation.yml when testing is done.
You can also create your own test picks manually using the same naming pattern.

Usage:
  python simulate.py --participants 5
"""

import argparse
import csv
import json
import os
import random

# ── Match data ────────────────────────────────────────────────────────────────
MATCHES = [
    (1,  'Mexico',                'South Africa'),
    (2,  'South Korea',           'Czech Republic'),
    (3,  'Canada',                'Bosnia and Herzegovina'),
    (4,  'United States',         'Paraguay'),
    (5,  'Haiti',                 'Scotland'),
    (6,  'Australia',             'Turkey'),
    (7,  'Brazil',                'Morocco'),
    (8,  'Qatar',                 'Switzerland'),
    (9,  'Ivory Coast',           'Ecuador'),
    (10, 'Germany',               'Curaçao'),
    (11, 'Netherlands',           'Japan'),
    (12, 'Sweden',                'Tunisia'),
    (13, 'Saudi Arabia',          'Uruguay'),
    (14, 'Spain',                 'Cape Verde'),
    (15, 'Iran',                  'New Zealand'),
    (16, 'Belgium',               'Egypt'),
    (17, 'France',                'Senegal'),
    (18, 'Iraq',                  'Norway'),
    (19, 'Argentina',             'Algeria'),
    (20, 'Austria',               'Jordan'),
    (21, 'Ghana',                 'Panama'),
    (22, 'England',               'Croatia'),
    (23, 'Portugal',              'DR Congo'),
    (24, 'Uzbekistan',            'Colombia'),
    (25, 'Czech Republic',               'South Africa'),
    (26, 'Switzerland',           'Bosnia and Herzegovina'),
    (27, 'Canada',                'Qatar'),
    (28, 'Mexico',                'South Korea'),
    (29, 'Brazil',                'Haiti'),
    (30, 'Scotland',              'Morocco'),
    (31, 'Turkey',                'Paraguay'),
    (32, 'United States',         'Australia'),
    (33, 'Germany',               'Ivory Coast'),
    (34, 'Ecuador',               'Curaçao'),
    (35, 'Netherlands',           'Sweden'),
    (36, 'Tunisia',               'Japan'),
    (37, 'Uruguay',               'Cape Verde'),
    (38, 'Spain',                 'Saudi Arabia'),
    (39, 'Belgium',               'Iran'),
    (40, 'New Zealand',           'Egypt'),
    (41, 'Norway',                'Senegal'),
    (42, 'France',                'Iraq'),
    (43, 'Argentina',             'Austria'),
    (44, 'Jordan',                'Algeria'),
    (45, 'England',               'Ghana'),
    (46, 'Panama',                'Croatia'),
    (47, 'Portugal',              'Uzbekistan'),
    (48, 'Colombia',              'DR Congo'),
    (49, 'Scotland',              'Brazil'),
    (50, 'Morocco',               'Haiti'),
    (51, 'Switzerland',           'Canada'),
    (52, 'Bosnia and Herzegovina','Qatar'),
    (53, 'Czech Republic',               'Mexico'),
    (54, 'South Africa',          'South Korea'),
    (55, 'Curaçao',               'Ivory Coast'),
    (56, 'Ecuador',               'Germany'),
    (57, 'Japan',                 'Sweden'),
    (58, 'Tunisia',               'Netherlands'),
    (59, 'Turkey',                'United States'),
    (60, 'Paraguay',              'Australia'),
    (61, 'Norway',                'France'),
    (62, 'Senegal',               'Iraq'),
    (63, 'Egypt',                 'Iran'),
    (64, 'New Zealand',           'Belgium'),
    (65, 'Cape Verde',            'Saudi Arabia'),
    (66, 'Uruguay',               'Spain'),
    (67, 'Panama',                'England'),
    (68, 'Croatia',               'Ghana'),
    (69, 'Algeria',               'Austria'),
    (70, 'Jordan',                'Argentina'),
    (71, 'Colombia',              'Portugal'),
    (72, 'DR Congo',              'Uzbekistan'),
]


# ── Knockout bracket data ─────────────────────────────────────────────────────

# Simulated R32 teams (M73–M88) — representative teams for testing only.
# In production, these come from knockout_bracket.json generated by parse_results.py.
R32_SIM_TEAMS = {
    73: ('Brazil',          'Morocco'),
    74: ('France',          'Norway'),
    75: ('Spain',           'Ecuador'),
    76: ('Germany',         'Switzerland'),
    77: ('Argentina',       'Mexico'),
    78: ('Netherlands',     'Senegal'),
    79: ('England',         'Ivory Coast'),
    80: ('Portugal',        'Colombia'),
    81: ('Belgium',         'United States'),
    82: ('Croatia',         'Japan'),
    83: ('South Korea',     'Saudi Arabia'),
    84: ('Uruguay',         'Egypt'),
    85: ('Turkey',          'Canada'),
    86: ('Austria',         'Sweden'),
    87: ('Tunisia',         'Ghana'),
    88: ('Panama',          'Australia'),
}

# Mirror of bracket.js topology (R16/QF/SF feeds)
R16_FEEDS = {
    89: (74, 77),  90: (73, 75),  91: (76, 78),  92: (79, 80),
    93: (83, 84),  94: (81, 82),  95: (86, 88),  96: (85, 87),
}
QF_FEEDS = {
     97: (89, 90),  98: (93, 94),  99: (91, 92), 100: (95, 96),
}
SF_FEEDS = {
    101: (97, 98), 102: (99, 100),
}

KO_MATCH_ORDER = (
    list(range(73, 89)) +   # R32
    list(range(89, 97)) +   # R16
    list(range(97, 101)) +  # QF
    [101, 102, 103, 104]    # SF, 3rd, Final
)


def simulate_ko_bracket(r32_teams):
    """Pick random winners round-by-round through the entire knockout bracket.
    Returns {match_num: winner_name} for all 32 matches (M73–M104).
    """
    winners = {}
    match_teams = dict(r32_teams)  # {m: (home, away)}

    # R32
    for m, (home, away) in r32_teams.items():
        winners[m] = random.choice([home, away])

    # R16 → QF → SF
    for feeds in (R16_FEEDS, QF_FEEDS, SF_FEEDS):
        for m, (f1, f2) in feeds.items():
            match_teams[m] = (winners[f1], winners[f2])
            winners[m] = random.choice([winners[f1], winners[f2]])

    # 3rd place: losers of both SF matches
    loser101 = (match_teams[101][0] if winners[101] == match_teams[101][1]
                else match_teams[101][1])
    loser102 = (match_teams[102][0] if winners[102] == match_teams[102][1]
                else match_teams[102][1])
    match_teams[103] = (loser101, loser102)
    winners[103] = random.choice([loser101, loser102])

    # Final
    match_teams[104] = (winners[101], winners[102])
    winners[104] = random.choice([winners[101], winners[102]])

    return winners


def generate_knockout_bracket(r32_teams):
    """Write data/knockout_bracket.json with confirmed=True and R32 teams."""
    os.makedirs('data', exist_ok=True)
    data = {
        'confirmed': True,
        'round_of_32': {
            str(m): {'home': home, 'away': away}
            for m, (home, away) in r32_teams.items()
        },
    }
    path = 'data/knockout_bracket.json'
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2)
    print(f'Generated knockout bracket → {path}')


def generate_knockout_picks(pool_id, participant_num, r32_teams):
    """Write a simulated knockout picks CSV for one participant."""
    folder = f'picks/knockout/{pool_id}'
    os.makedirs(folder, exist_ok=True)
    filename = f'{folder}/wc26_knockout_simulation-{participant_num}.csv'
    winners = simulate_ko_bracket(r32_teams)
    with open(filename, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['match', 'winner'])
        for m in KO_MATCH_ORDER:
            writer.writerow([m, winners.get(m, '')])
    print(f'  Generated: {filename}')


def random_outcome():
    return random.choice(['W1', 'Draw', 'W2'])


def outcome_label(outcome, t1, t2):
    if outcome == 'W1':   return f'{t1} win'
    if outcome == 'Draw': return 'Draw'
    return f'{t2} win'


def random_score(outcome):
    if outcome == 'W1':
        h = random.randint(1, 4)
        a = random.randint(0, h - 1)
    elif outcome == 'W2':
        a = random.randint(1, 4)
        h = random.randint(0, a - 1)
    else:
        s = random.randint(0, 2)
        h = a = s
    return h, a


def generate_picks(pool_id, participant_num):
    folder = f'picks/group/{pool_id}'
    os.makedirs(folder, exist_ok=True)
    filename = f'{folder}/wc26group_{pool_id}_simulation-{participant_num}.csv'
    with open(filename, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        for num, t1, t2 in MATCHES:
            outcome = random_outcome()
            label   = outcome_label(outcome, t1, t2)
            writer.writerow([num, f'{t1} v {t2}', label])
    print(f'  Generated: {filename}')


def generate_ko_results(r32_teams):
    """Write results/knockout_results.csv with simulated winners for all 32 KO matches."""
    os.makedirs('results', exist_ok=True)
    path = 'results/knockout_results.csv'
    winners = simulate_ko_bracket(r32_teams)
    with open(path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['match', 'winner'])
        for m in KO_MATCH_ORDER:
            writer.writerow([m, winners.get(m, '')])
    print(f'Generated results for all 32 KO matches → {path}')


def generate_results():
    os.makedirs('results', exist_ok=True)
    path = 'results/group_results.csv'
    with open(path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['match', 'home_score', 'away_score', 'outcome'])
        for num, t1, t2 in MATCHES:
            outcome    = random_outcome()
            home, away = random_score(outcome)
            writer.writerow([num, home, away, outcome])
    print(f'Generated results for all 72 matches → {path}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--participants', type=int, default=5)
    parser.add_argument('--stage', choices=['group', 'knockout', 'all'], default='all',
                        help='Which stage to simulate (default: all)')
    args = parser.parse_args()

    if args.stage in ('group', 'all'):
        print(f'\nGenerating {args.participants} participants × 2 pools (all 72 group matches)...')
        for pool_id in ['swiftly', 'fandf']:
            print(f'\n  Pool: {pool_id}')
            for n in range(1, args.participants + 1):
                generate_picks(pool_id, n)
        print('\nGenerating results for all 72 group matches...')
        generate_results()

    if args.stage in ('knockout', 'all'):
        print(f'\nGenerating knockout bracket (confirmed R32 teams)...')
        generate_knockout_bracket(R32_SIM_TEAMS)
        print(f'\nGenerating {args.participants} participants × 2 pools (all 32 knockout matches)...')
        for pool_id in ['swiftly', 'fandf']:
            print(f'\n  Pool: {pool_id}')
            for n in range(1, args.participants + 1):
                generate_knockout_picks(pool_id, n, R32_SIM_TEAMS)
        print('\nGenerating results for all 32 KO matches...')
        generate_ko_results(R32_SIM_TEAMS)

    print('\nDone. Run aggregate_picks.py next to update the leaderboard data.')
